### ISSUE TITLE
General: Some super privileges needed to import dumps containing statements like "create view" 

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#102]
Hello team,

This afternoon I tried to import a MySQL . DB and it failed with the following message:

> ---------- Forwarded message ----------
> From: XXXXXXXXX
> Date: Fri, May 26, 2017 at 3:25 PM
> Subject: [Cloud DB] Importing "gel_mount" failed
> To: XXXXXXXXXX
> 
> 
> Import database failed
> 
> Your request to import a(n) "mysql" database named "gel_mount" has failed with the following message:
> 
> "Importing dump failed: could not execute import command: Warning: Using a password on the command line interface can be insecure.\nERROR 1227 (42000) at line 17600: Access denied; you need (at least one of) the SUPER privilege(s) for this operation"
> 
> We're sorry for the inconvenience caused.
> 
> Visit Cloud DB.

The import worked on my local machine. I shared the database used to trigger the error on the CloudDB with Daniel Javorszky.

Thanks !

**Comment by sorin-pop** [comment]
Dani, doesn't this have to do with the security modification you made today?

**Comment by djavorszky** [comment]
No, this is different. The fix today was about forbidding users to specify tables / usernames that are for mysql (e.g. "root" for user or "mysql" for database name).

The dump contains instructions to create a view that requires elevated privileges - that we don't provide, given how we only grant database level privileges to the user.

I've taken a look at the available permissions, perhaps we can grant some super privs that would still catch malicious attempts

**Comment by balcsida** [comment]
I just want to report that I experienced the same bug.
`Importing dump failed: could not execute import command: mysql: [Warning] Using a password on the command line interface can be insecure. ERROR 1227 (42000) at line 17600: Access denied; you need (at least one of) the SUPER privilege(s) for this operation`

**Comment by djavorszky** [comment]
Thanks @balcsida! Can you share the location of the dump with which this issue arose? If I make a change, I'd like to be able to see if that's resolved as well :)

**Comment by balcsida** [comment]
tmp\balcsida\dnn_killer.sql on R2-D2

**Comment by djavorszky** [comment]
Did some further digging: The issue is with the following line:
`/*!50013 DEFINER=`root`@`localhost` SQL SECURITY DEFINER */`

According to [MySQL](https://dev.mysql.com/doc/refman/5.7/en/stored-programs-security.html), if a DEFINER is set, then the privileges of the defined user is used when creating the view (and others), otherwise, the privileges of the current user.

Due to this, we'd need to grant Super (i.e.: all) privileges to the user executing the import, which we decided early on not to do due to security reasons.

I've implemented a solution that removes lines that have the "DEFINER=" string in them - this way, the import finished successfully. However, this is not a full featured solution, as it'd also remove lines that have these in e.g. text fields (this very comment would be removed for example).

At this point, there are two options.
1. Grant super to the importing user
2. Remove lines containing "definer=" string and deal with the side effects
3. Write the stringfinder-remover in a way that only removes the lines we want to remove.

@sorin-pop, @zsoltbalogh, what do you think? I'd go with either 2 or 3 to be honest - 2 in the short run, 3 in the long one.

/note, if we choose 2 (or 1), I can push that to prod in about a day.

**Comment by sorin-pop** [comment]
I think 2 should be good enough, there's only a small chance that some stored data will contain this substring. So I guess the side effects will really be minimal. Maybe if we add 'SQL SECURITY DEFINER' to the check, the chances will be perhaps even smaller that some real database data contains 'DEFINER=' and 'SQL SECURITY DEFINER'.

Actually, I don't really have a problem with 1 either, if that grant is temporary, only for the duration of the dump import.

**Comment by zsoltbalogh** [comment]
We can have a better removal for the definer as all lines would start with this code:
/*!50013 DEFINER=

I think it's a pretty obvious match. There might be other numbers, however we can look into that once we find them.

**Comment by djavorszky** [comment]
Thanks for the input! I went with checking for `50013 DEFINER=`, see 1910190e7cd974ac8acf509c9be753d083560aa5

Implemented, but not pushed to production yet.

**Comment by sorin-pop** [comment]
The question such definer lines always look like this, always with that number: 50013. If yes, then I think this is a good solution.

**Comment by djavorszky** [comment]
Seems so.. googling for `50013` returns a lot of "CREATE DEFINER" statements. The other way around is not so clear, usually there isn't any number next to them..

If this issue comes up again with different number, we'll recheck
