### ISSUE TITLE
MySQL Dump import fails if there's a create command at the beginning of the dump

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#151]
Steps:
1. Go to Import Dabase, choose mysql-56
2. Try importing the dump file at r2d2/tmp/sorin/Dump20170717.sql

I used parameters:
database name: upgrade_
user name: sorin
user password: test

Error message shown when cliking on Why? is:

Importing dump failed: could not execute import command: Warning: Using a password on the command line interface can be insecure. ERROR 1044 (42000) at line 1: Access denied for user 'sorin'@'%' to database 'upgradetraining'

If I removed the create command from the beginnning of the dump, its import went without problems.

Dani, any idea? As far as I remember, you actually handled this kind of use case, to ignore the create commands in the dumps, isn't it?

**Comment by djavorszky** [comment]
Yeah, should be removed... seems like it's not being matched, or if it is, not being removed. Should be taken care of during validation.

I managed to reproduce it with the provided dumpfile, so will be able to test it soon.

**Comment by djavorszky** [comment]
The good news is that I found the root cause... the bad news is that it's going to be a complicated fix.

Here's a high level overview of wihat's happening:
1. Check file for occurrences of "create database", "alter database", "use", etc.
2. Grab all the line numbers
3. Copy the file line-by-line, without the occurrences previously found.

Basically: Remove all occurrences of the problematic lines.

Here's the issue: In the helper library I'm using (that I wrote: [sutils](https://github.com/djavorszky/sutils)), everything is passed around as an io.Reader, because it makes sense to be able to pass anything that satisfies the io.Reader interface.

The problem, however, is that once io.Reader is read till the end (e.g. EOF), it is not reset, meaning, that subsequent reads will return an empty string. This makes it impossible to check multiple multiple strings.

I've been looking into the possibility of either resetting the io.Reader (e.g. with switching to a bufio.Reader, [which has a Reset method](https://golang.org/pkg/bufio/#Reader.Reset)), or to any alternatives, e.g. only iterating through the reader once and checking everything in that iteration.

Hopefully I should have something soon.
