### ISSUE TITLE
Oracle VM out of space

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#153]
"Downloading file failed: downloading file failed: write dumps/STAGELRP1.dmp: There is not enough space on the disk."

@sorin-pop, can you take a look at it please?

**Comment by sorin-pop** [comment]
Hi Dani,

I have looked into it. Indeed the disk space was eaten up by the Oracle tablespace in which we do the imports. The tablespace grew (autoextended) until there was no more space left on the disk. This prevented the successful copying of the dump file to the server.

I tried freeing up space by dropping a couple of very large databases, but I could see no increase in the disk space. It turns out that in this case the tablespace hangs on to that disk space (assuming that it will be needed later) and it should be reclaimed. I am currently looking into how to do that.

We also discussed that I will create some kind of job that can be run weekly, for example, which would deal with reclaiming disk space held by the tablespace, so that the dump files have enough space to be copied over before being imported.

**Comment by sorin-pop** [comment]
So far it looks like it's not an easy matter to reclaim disk space from the oracle data files, so I don't know how long it will take for me to get more familiar with the procedure and apply it. As much as my time allows it, I'll keep working on this. But it might be possible that an easier (and faster?) solution for the moment would be to somehow extend the disk space of that Oracle VM (but I'm also not sure what are the possibilities for that, and how it can be done. Our system administrator Péter created this VM back then, and he's no longer here...who do ou think could perhaps help with this? @balcsida ? Bz?)

**Comment by sorin-pop** [comment]
We have handled this issue for now (coupled with the solution on #154 ). But we'll still need more disk space added to that VM, nevertheless. I am closing this ticket now.
