### ISSUE TITLE
Allow importing from multiple dumps in case of oracle

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#163]
Per #161, the Oracle connector is now able to import a database from multiple dump files.

The server and connector is not ready to handle multiple files however, so we'd need to introduce this possibility.

This won't be a small feat, however, because:
1. The server only allows uploading one file
2. The server only allows selecting one file
3. The server only sends a single URL to the connector to download
4. The connector only anticipates a single URL
5. The connector freaks out and fails if there are multiple files in an archive
6. This only needs to be implemented for Oracle, but not others.

We may be looking at a bigger refactor.

**Comment by sorin-pop** [comment]
Yes, I thought so, that's why I did not go into this part and rather "left it to you" :) And taking into consideration the fact that very seldom we get exports made into multiple dump files (so the feature will be very rarely needed, it seems now), this really looks like too much hassle for almost nothing. However, it would be really nice and professional to have this feature though. As you think, Dani.

**Comment by sorin-pop** [comment]
I just received a dump in 3 files from a customer. Could be that this won't be such a rare use case after all, especially as the customers' database will grow bigger and bigger.

**Comment by sorin-pop** [comment]
Migrated to https://github.com/djavorszky/liferay-support-ee/issues
