### ISSUE TITLE
Possible superfluous call to db.CreateDatabase in case of Oracle

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#190]
The import_dump stored procedure already contains the user (and tablespace) creation command (after trying to drop them). I think that calling db.CreateDatabase in handlers.go/importDatabase func could be left out for Oracle (if we can check that there). Because like this, I think the following is happening:
- it creates the tablespace and the user (create_schema.sql)
- it drops them (import_dump.sql)
- it creates the tablespace and the user (import_dump.sql)

We can also think about leaving it, but then removing this part from the import procedure. Although there might be a reason I did it like this back then (?). I'm not sure, can't remember. But it certainly looks like it is doing superfluous things now. And since we introduced the "one tablespace for each user" approach, the creation/dropping process is a bit longer (because the tablespace+2 datafiles creation dropping takes a few additional seconds)

This thought came up because today Jándi Tibi ran into:

Importing dump failed: Dump import seems to have failed: > stdout: 'An error has occurred: ORA-01543: tablespace 'DEGUSSA93_TIBI' already exists

although we don't know how. We tried to reproduce it by doing the import exactly like he did, but could not reproduce this error again. But I am thinking that perhaps the fact described above could cause this error under some circumstances.

What do you think @djavorszky ?

**Comment by djavorszky** [comment]
Logically speaking, create, drop, create should not result in a "tablespace already exists" error, unless:
1. tablespace already existed before first step
2. tablespace was not dropped at second step

Because of this, I don't think this is the root cause of the issue you faced.

Given how the issue is about the possible superfluous call, then let's talk about performance: I would like to try and avoid adding implementation specific code to the general handlers if possible, so this would have to be handled in oracle.CreateDatabase (or oracle.ImportDatabase).

Adding the check to the first would have to be done in such a way that the call is aware that it's creating a database for an import process instead of just a create one. For that, we'd need to refactor the code to add in a [context](https://golang.org/pkg/context/) and then store a bool for this matter. This would be a bigger refactor affecting all implementations for something that only oracle would use (for the time being). Due to this, I'd rather not add the context.

Removing the drop from the import_dump.sql would be a better candidate - I think the reasoning behind having that was that it should not error out if what you try to use already exists - that makes development much faster (you only need to call one procedure instead of two for example).

You mention that we'd be saving 1-2 seconds... As far as I can see, this is async time, meaning, that the user's browser does not wait for the result of the create database, as it happens in the background. 

1-2 seconds is minuscule compared to the overall time of an Oracle import - unless you are absolutely sure that this is the root cause of the failed import, then let's fix it, otherwise, I don't think we should pour too much energy into resolving it.

For the record, the "create database" call at the beginning of an import process is added to prepare the scene for the import process, as that does not actually do the database creation - it just assumes that everything is ready for it to do its job.

**Comment by sorin-pop** [comment]
Yes, let's put this aside, I'm also not sure we should change this, and that it was the cause of Tibi's error (s you said, theoretically it shouldn't)
