### ISSUE TITLE
Allow exporting DB dump from interface

### ISSUE THREAD

**Issue by alfonsocrisci** [djavorszky/ddn#191]
Sometimes I need to get an export of the database created on the cloud. In order to do that, I should proceed locally from my client. It would be nice to be able to do this from the interface on the CloudDB site instead.

My use-case: I have MySQL 5.5 locally, but want to export 5.6 dump, MySQL workbench warns me:

![image](https://user-images.githubusercontent.com/7203657/29807433-4d08bed2-8c94-11e7-9be0-7b21c7c22f16.png)

To solve this, I use a VM where MySQL 5.6 is installed and proceed with the export from there.

Thanks !

**Comment by sorin-pop** [comment]
Yes, this is a very good feature request. It also occurred to me a couple of times, that perhaps it would be nice to add export functionalty as well. 

On the UI, I guess it would be simply a new action icon on the right, next to the others. When user clicks on it, an export of that database is initiated in the background. When the export is finished (successfully), user gets an email with a direct download link to the created dump file.

**Comment by djavorszky** [comment]
Agree with @sorin-pop, great idea. Also, thanks for summarizing how it should be handled, I think we'll go with that :-)

One note though, we'll have to think about where exactly the dump will reside and for how long, as these files can be quite big.

**Comment by sorin-pop** [comment]
I guess they could reside in the server's dumps folder, or in a subfolder dumps/exports, or in a separate folder (e.g exports) next to the dumps folder. And probably for not too long, max 24 hours (and the user will be warned that he has 24 hours to download it). Or should we put the on the mounted folder (currently r2d2/ftp/(clouddb_exports)) so that the user can right away use it for an import?

**Comment by sorin-pop** [comment]
I started working on this, from the agent side, however I am having difficulty with figuring out how to do the transfer of the dump file (after having been zipped) from the agent to the server. The current infrastructure seems to be only prepared for the other way around (which is what we needed so far). 

As far as I can see, the transfer from server to agent is happening something like this:
- server calls agent's ImportDatabase func, and passes to it the URL to the file stored on the server, in the web/dumps directory (which is enabled as a route for static file sharing as a file server).
-agent uses this URL to download the file from the server, with the inet.DownloadFile func

@djavorszky , how should we go about doing this the other way around? Should we also "open" agent's exports directory as a file server, and then pass the URL to the server, and then the server uses it to download the file with the same inet. DownloadFile utility func?

Or should we "push" somehow the file directly to server's mount-loc directory (e.g. under a clouddb_exports subdirectory)?

Here is what I did so far: https://github.com/djavorszky/ddn/pull/258

**Comment by djavorszky** [comment]
Hi @sorin-pop,

I don't think that we should send the file to the server or to have the server download it. We should simply open a folder and serve static files from there, and share its link with the end user. The delete-after-n-hours logic should be running on the server, having its own table to keep track of the agent-filename-exportTimestamp information (and possibly others).

What do you think?

As for the implemented logic so far, I have three suggestions:
1. There is no need to pass an exportTimestamp to the ExportDatabase - it can simply call "time.Now()" if and when its needed
2. Can you explain why both dumpFileName and fullDumpFileName are needed? I think only having the fullDumpFileName should be enough, and extract the "dumpFileName" from it if needed.
3. When working on the new API, I added an "[inet.SendSuccess](https://github.com/djavorszky/ddn/blob/master/common/inet/inet.go#L112-L122)" and "[inet.SendFailure](https://github.com/djavorszky/ddn/blob/master/common/inet/inet.go#L112-L122)" methods, which will result in the API response pattern used in the new API - can you please use those? For example usage, see [this](https://github.com/djavorszky/ddn/blob/master/server/apiv2.go#L68-L83).

Dani

**Comment by sorin-pop** [comment]
"I don't think that we should send the file to the server or to have the server download it. We should simply open a folder and serve static files from there, and share its link with the end user."
I'm fine with that, however, I am wondering how this will fit in with a typical use case, when the user will want later on to import such a dump? If they downloaded it to their computer, and the dump is large, they will not be able to imp[ort it with the Upload method. But neither with the Browse method, as the dump is not on the FTP server: so they would have to manually copy it to a folder on the FTP server... What do you think?

As to the further questions:
1. I wanted to use the that start variable and pass it (formatted) to the ExportDatabase func, because later on we also use that same variable for logging the duration of the process:

`logger.Debug("Import succeded in %v", time.Since(start))`

So I thought it would be somewhat more consistent to use only one/the same start timestamp for the dump filename as well. 

But indeed, this really doesn't matter too much. I can also not pass it, and instead, inside ExportDatabase get a time.Now() once again, and use that for the filename. (I just didn't feel like doing two different time.Now()'s, when there is already one just before invoking ExportDatabase, so I though I'll just use that and pass it to the export func)
Please let me know, I'm OK either way, it doesn't really make much of a difference, I guess.

2. True, it's kind of overcomplicated with these two variables. fullDumpFileName is the file name with the extension (e.g ticket_timestamp.dmp), while dumpFileName is the same, without the extension (used outside ExportDatabase to add a .zip extension to it when when we zip it, and inside ExportDatabase to add a .log extension to it when defining the expdp output log file). But yeah, I guess it's really not necessary, and whenever I want the name without the dump extension, I can just call something like file.Base(fullDumpFileName) I guess (although I'm not sure if this expects a full path though...). I'll work then on eliminating this additional variable and returned value by ExportDatabase.

3. I will look into that, and get back to you if I have questions.

**Comment by djavorszky** [comment]
Conceptually speaking, we'd only keep the dumps for a limited time anyway, so whether it resides with the agent or the server doesn't really make or break the deal. If the user wants to save the dump, they'd have to put it on the mounted folder next time they want to import it. If they want to reimport it immediately, then simply export-import, no need to move the file through the network (we can have a seperate action for this).

As for the timestamp, I'm fine with having two seperate timestamp calls, one for the filename, the other for logging how long it all took.

And yes, deriving the "base" of the file is completely fine. Sure it's an extra step, but we don't overcomplicate the API.

Let me know if you have any further questions or concerns.

**Comment by sorin-pop** [comment]
OK, I changed the code as per your recomendations regarding the timestamp usage and fullDumpFileName /dumpFileName.

> Conceptually speaking, we'd only keep the dumps for a limited time anyway, so whether it resides with the agent or the server doesn't really make or break the deal. If the user wants to save the dump, they'd have to put it on the mounted folder next time they want to import it. 
That's cool with me, I agree. And it makes it simpler.
However, for the same reason, I was thinking that perhaps the below:

> The delete-after-n-hours logic should be running on the server, having its own table to keep track of the agent-filename-exportTimestamp information (and possibly others)

might not be necessary. It seems a little bit too much to build such a serious infrastructure (new db table on the server, etc) for keeping track of these quite "volatile" (24h) export dumps, and for controlling their deletion (unless we want to show them on a page on the UI...). Perhaps instead it would be simpler to implement such a  delete-after-n-hours logic **on the agent**, that would simply go through the agent's exports folder, and delete every file older than 24 (or n) hours. Just a thought, I'm not sure...Probably I'll be able to have a better picture about this as I go along with the implementation, which I will resume soon, when I'll have time.

**Comment by djavorszky** [comment]
> Perhaps instead it would be simpler to implement such a delete-after-n-hours logic on the agent

You're right - the easiest method would actually be to create a goroutine once export completed to sleep for n hours and just delete the file after that. Also to delete all exports at startup (in case it crashed while such a goroutine was running).

There are a couple of things we need to consider however:
1. Should we allow users to start a reimport if an export is available? If so, we need to keep track of the file. I think one of the original request was just this: reimport with a click.
2. When deleting, we have to check if the file is being used for an import, and delay deletion if so

Let's further discuss this in person, when you have time.

**Comment by sorin-pop** [comment]
Hi,

I worked further on this, please find below a new pull request.

Basically, I rather focused for now on implementing the "core", basic level of this feature, from agent to UI. So now the user can initiate an export fromthe UI, and then get an email with a working link to the generated dump.

I implemented the export itself for Oracle (successfully tested). I also implemented it for MYsql as well, in order for you to be able to test on your machine, @djavorszky. Please note, it didn't work for me, I think because I have two MySQL servers running on my machine. I expect the code should work in a real environment (only one server running on the agent machine), but who knows, it might still need some tweaking (e.g. should we simply call mysqldump assuming that it is in the PATH, like now, or add the path to it as a new property in the conf file?).

I think the other subjects related to this feature: if we should save to meta-database the info about the exports or not, how to handle the cleaning of old dumps, etc. should be handled on separate, new tickets. (this is a massive new feature, it's difficult to implement and discuss everything under one ticket, one pull request) 

New pull request: https://github.com/djavorszky/ddn/pull/258

**Comment by djavorszky** [comment]
Thank you @sorin-pop! I've merged it, added the API version, and implemented a checker that deletes the exports after 72 hours. For now, I've hidden the export button per last commit, because as we discussed, we're not exactly sure how we should handle if an export fails - whether the status should stay in "Completed" or not.

Thinking about it, I think the "Completed" status is simply redundant, and we may be approaching statuses the wrong way. The general idea is that a database may be "usable" nor "not usable".

"Usable" would simply mean that clients can connect to it, which is the case when the database has been successfully created or imported, but also when an export is in progress.
"Not usable" would be everything else - import/create in progress, or any failed status.

And then we could sub-status these, e.g. specify why a database is unusable or a usable database being exported at the moment. What do you say? I'm not sure. Just thinking aloud. Also, even if we go with this, I don't like the usable/unusable statuses, they sound silly, so we may want to look for better ones.

**Comment by djavorszky** [comment]
cross-posted relevant section to #267. Since this has been implemented (but hidden [though one can unhide it and there's also the API per [the documentation](https://github.com/djavorszky/ddn/blob/master/server/apiv2.md#export-a-database) {which contains wrong success example, I'll fix that soon}]), do you think we can close this issue?

**Comment by sorin-pop** [comment]
Yes, I guess we can close it. 

@alfonsocrisci , this doesn't mean that you will be able to use this feature right away. But hopefully it will be available soon.
