### ISSUE TITLE
Handle multiple (per table) Mysql dump files

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#206]
In MySql it is possible to export a database into multiple sql dump files, one for each table. It happens very rarely that we get such dumps from the customers, but perhaps we could enhance CloudDB to be able to handle such use cases as well.

**Comment by sorin-pop** [comment]
I googled a bit and it seems like such exports can be made with a mysqldump command like this:

`mysqldump --user=dbuser --password --tab=~/output/dir dbname`

However, "After running the above, you will have one tablename.sql file containing each table's schema (create table statement) and tablename.txt file containing the data." (https://stackoverflow.com/questions/3669121/dump-all-mysql-tables-into-separate-files-automagically)
This is confirmed by the official documentation of mysqldump: https://dev.mysql.com/doc/refman/5.5/en/mysqldump.html#option_mysqldump_tab

**Comment by djavorszky** [comment]
We could implement this, basically the same as #163 but for MySQL.

The same is true here as there: we need to alter the import process to allow multiple files to be in an archive and then we'd need to make sure that they are all imported.

Alternatively, since MySQL dumps aren't binary, we could simply cat them together into one file and then pass that along to the importer.

**Comment by djavorszky** [comment]
Migrated to https://github.com/djavorszky/liferay-support-ee/issues/15
