### ISSUE TITLE
Failed to drop oracle database: cannot drop a user that is currently connected

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#207]
Not sure how this happened - I suppose the drop command came when the user was still connected.

See public databases for two instances.

The issue here is two-fold:
1. ~~There's no way to re-drop the database if the first time it failed for whatever reason~~ nevermind, spoke too soon. It's possible, but not for me - I'm not the owner :disappointed: 
2. According to the creator of these schemas, they weren't connected to the database at that time, so there's a potential issue there as well. @sorin-pop, can you please take a look at this?

**Comment by sorin-pop** [comment]
I have looked around, what they say that should be done in such a situation is to list the open sessions of that user (v$session view) and then kill them, after that the drop user command will work. Although some say that they did not find any opened sessions.

I have the necessary queries,scripts for doing this, and I guess we could incorporate it in our dropping script. But I'm not sure we should complicate it like this...unless it really turns out that this is occurring quite often.

For some reason today Csilla could drop those two databases without any problem (and I also haven't found any opened sessions in the background), so I could not really "catch" the issue and properly investigate it for now. Maybe I would wait a little bit, to see if it resurfaces again...

I don't know, what do you think?

**Comment by djavorszky** [comment]
Since this was the first occurrence and, as it looks like time resolves it, I think we should close this case. The worst case scenario is that the database will be dropped later, and in the meantime, it'll occupy space on the disk.

@sorin-pop, if you agree, feel free to close the issue.
