### ISSUE TITLE
connector: During import, connector should ping server every n minutes

### ISSUE THREAD

**Issue by djavorszky** [djavorszky/ddn#25]
Import can take a very long time, and as such, messages between two steps (e.g. starting import and finishing import) can have a huge pause.

In order to detect fails fast, the connector should be able to send a ping every n (minutes, configurable) that is nothing more than an "I'm still here and I'm still working" message.

This way, the server can listen to the actual messages but also receive the heartbeats. If the server doesn't receive a heartbeat after a given time, it will know that the connector went down. It can then double check to see if that's indeed the case and report the failure.

**Comment by sorin-pop** [comment]
For Oracle import, there's always a job entry created in a system table, which shows the current status of the import job. So we can check the status of the import by querying those job records. I will need to work on this, because currently my Oracle import scripts are written in a synchronous way (the script waits for the import job to finish, and only after that it returns back). The code lines for starting the import asynchronously are already there (currently commented out), and I'll need to implement the status querying part.

Additionally, my Oracle import script calls the import with the logging option, so the import job is logging what it is doing into a text file placed next to the dump file, on the machine running the Oracle server. So the user will also have the possibility to check the progress by taking a look at this log file once in a while, provided that we'll tell him where to find it, and we give him read access to it.

**Comment by djavorszky** [comment]
That's a bit more complicated than what I initially had in mind, but also, only applies to Oracle.

I would not like to provide even read access to logfiles. Ideally, end users should only be able to reach the server itself, never the connector. In the future, if we can somehow post relevant updates even while the import is running, then we should implement it. Until then, a simple statusupdate is enough.

Also, regarding:
> currently my Oracle import scripts are written in a synchronous way (the script waits for the import job to finish, and only after that it returns back). The code lines for starting the import asynchronously are already there (currently commented out), and I'll need to implement the status querying part.

First, let's make it work in a synchronous way. Later we can get the connector to spawn another goroutine and query the status alongside the import process.

For now, we can implement this by doing something along the lines of:
```
channel := make(chan string)
ping := time.NewTicker(time.Minute)
var msg string
for {
	select {
	case msg = <-channel:
		fmt.Println("Received msg:", msg)
	case <-ping.C:
		fmt.Println("ping!")
	}
}
```

What do you think of this approach?
Dani

**Comment by sorin-pop** [comment]
Hmm.. I don't really understand, except that the oracle import script can remain synchronous.

**Comment by djavorszky** [comment]
Yup, exactly :)

**Comment by djavorszky** [comment]
Since the last update, the server now checks for the availability of the connectors and reports if they disappear. This doesn't necessarily mean that the connectors are down, but is a good indication. For now, I'm closing this issue as no longer necessary.
