### ISSUE TITLE
[UX] Better Oracle name/db_name handling

### ISSUE THREAD

**Issue by balcsida** [djavorszky/ddn#257]
It is not obvious to the user that the DB name will not be used and random user will be generated.
![257](https://user-images.githubusercontent.com/1768446/35631212-9ddd64aa-06a3-11e8-9e03-00a47241a8d9.gif)

**Comment by sorin-pop** [comment]
I think the issue depicted in the video is a somewhat edge-case:
1. user selects a database type other than Oracle
2. he then fills in the "Database name"
3. then he "changes his mind" and selects Oracle
Result: The "Database name" field is correctly greyed-out and disactivated. However, the name typed at step 2 remains there (but will be of course ignored in the background)

Therefore, I think that, in order for this to not be confusing for the user, we should simply make a UI change so that at step 3, the "Database name" is **automatically cleared** before being disabled.

Please also note that:
- it is not good user practice to leave the fields blank and rely on automatic random name generations (I would argue that this was a mistake to make it like that. @djavorszky told me that he did it that way because the original ClouDDB made by Gyula was also functioning like this. But I think it encourages irresponsible user behaviour, and well, confusions like this one)
- when user select oracle, there are informational tooltips that explain to him how the fields work in this case (so user should also pay attention to them)

**Comment by djavorszky** [comment]
One note: the default selected database is "empty", the user has to choose one - In that step, they can still write anything there.

So there are easy, straightforward, and complicated solutions to this.
Easy, straightforward:
1. As Sorin mentioned, clear the databasename when selecting Oracle
2. Similarly to 1, if dbname is populated but dbuser is not, copy dbname to dbuser (and vice versa)
3. Disable all inputs until a database is selected

Complicated:
1. Make the creation a multi-step process, like an install wizard.
2. Remove the autogeneration and fail early (bit more complicated as not all forms are created equal [e.g. Oracle, MSSQL]
3. Remove autogeneration, fail early, but also introduce an option to "save credentials" for future use.

At this point I'd say let's go with one of the easy and straightforward ones and then think about how to properly address this in the future UI.

**Comment by balcsida** [comment]
Issue migrated
