### ISSUE TITLE
import of Oracle zipped dump fails with server error after unzip

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#45]
Use this, for example: r2d2/tmp/sorin/liferay170215.zip

It seems like after unzipping, the dmp file is not put in the same directory (home dir of the user).

The problem is that the sql script is passed nothing as the first parameter, the directory where the dump is.

It should look like this:

2017/03/17 06:48:25 Running command:  C:\app\Administrator\product\12.1.0\dbhome_1\BIN\sqlplus.exe [-L -S system/password @./sql/oracle/import_dump.sql C:\Users\liferay/ liferay170215.dmp sorin2 test LIFERAY_DATA]

so it is passed C:\Users\liferay/

But with zip, it is called like this:

017/03/17 06:36:21 Running command:  C:\app\Administrator\product\12.1.0\dbhome_1\BIN\sqlplus.exe [-L -S system/password @./sql/oracle/import_dump.sql  liferay170215.dmp sorin1 test LIFERAY_DATA]

As you can see, there is nothing before the dump file parameter, and this makes the sql script fail. It expects the directory where the file is, as the first parameter, but with zipped dmp, this is empty for some reason.

Dani, any idea why?

**Comment by djavorszky** [comment]
I believe it's because when extracting the file from the archive, it is placed next to the connector's executable and is passed on to the corresponding import processes without a PATH - since the file is right there.

With Oracle, since the import script is in another directory, I believe this can cause an issue.

We should either specify the file to have the full path if it's in the same directory OR move the file into a temporary directory after it got extracted (or not, if it's not an archive). For example, `os.TempDir()` sounds like a good candidate. This way, since the file will be in another directory it'll have a PATH.

At least.. that's a guess. Do you wanna have a go at it @sorin-pop or want me to check it out?

**Comment by sorin-pop** [comment]
I'll have a look first.

**Comment by sorin-pop** [comment]
I haven't had the chance to debug this locally yet, but I think that, based on what you said, it's pretty clear what's happening.

So in the case of a zipped dump, in oracle.go/ImportDatabase, dbRequest.DumpLocation will not contain the whole path, but just the unzipped dump file name.

That's why:

dumpDir, fileName := filepath.Split(dbRequest.DumpLocation)

will return an empty dumpDir, and that's why this argument is empty when passed to import_dump.sql.

Possible remedies:
1. We ensure that even in this case, dbRequest parameter's DumpLocation field includes also the path to the unzipped dump file.
2. Or we don't, and I modify that code at the beginning of oracle.go/ImportDatabase, to check if dumpDir is returned as empty after calling filepath.Split. If yes, then I just get the current working directory of the connector exe and put that in dumpDir.

However, these two solutions have a slight drawback, because the Oracle import script is creating log files for each import, and it is placing them next to the dump file (so in the dumpDir that we pass to the script). Therefore, in case of unzipped dump files, the Oracle import logs will be created in the user's home directory, and in the case of zipped ones they will be put in the connector exe's directory. Which doesn't sound very nice.

Of course, if really needed, I can modify the PL/SQL code to somehow overcome this, but this might not be so simple as it looks at first sight, and I'm afraid of introducing new issues with this.

So actually I would rather argue on the following point:

- isn't it somehow inconsistent logic that we have different behaviour in the connector in case of simple dumps, and respectively zipped ones? Why, in case of zipped ones, we place the unzipped dump next to connector.exe, and don't rather put it in the user's home directory, so in the same place where we downloaded the zip file from the server? And just simply populate and pass the dbrequest.DumpLocation field with the whole path to this file, the same way as in the first case (unzipped)? Was there some specific reason why you made it like this, is this really necessary for some reason?

**Comment by sorin-pop** [comment]
Oh, I just realized there's another big problem with this. It's not good if we keep passing different dumpDir's to the Oracle import script, because it contains an instruction like this:

CREATE OR REPLACE DIRECTORY DATA_PUMP_DIR AS <dumDir>;

So it always creates (replaces, actually) a DIRECTORY database object with name DATA_PUMP_DIR, pointing to the given OS directory. And I don't drop this DIRECTORY object.

So if two users initiate an Oracle import almost at the same time, one with a zipped dump, one with an unzipped dump, the place to which  DATA_PUMP_DIR points is changed and it can cause (concurrency) issues.

If we always pass the same dumpDir, there can be no problems. (But of course I realize that in this case running this instruction for every import is somehow redundant, but it is very fast and it cannot cause any problems. But if we agree that the dumpDir will always be the same, so the directory where the Oracle dumps will end up will always be the same, I can remove this instruction, and this DIRECTORY object will always be there, with the same name and pointing to the same OS directory.)

So options 1 and 2 above could run into this issue with concurrent user imports. So this is another argument for rather handling this at the connector side, by somehow ensuring to always pass the same dumpDir.

But of course, I could also handle this somehow in the Oracle code, like always creating a DIRECTORY object with a unique name for every import. And then I would need to take care of also dropping this object in the end (or when there's an exception), so that we don't accumulate hundreds, thousands of DIRECTORY objects in the Oracle database as time passes. But this also sounds a bit scary to me, and I fear I would introduce some other problems with this. I am happy that these Oracle scripts are finally quite stable by now, és nagyon nem bolygatnám őket, ha lehet. So I would still rather push for a change in the Go code, if possible and appropriate.

**Comment by djavorszky** [comment]
Hi Sorin,

This issue stems from two "decisions" I made in the past (or, should I say, by being lazy 2 times):
1. Downloading a file ends up in the user's home directory (see [here](https://github.com/djavorszky/ddn/blob/master/connector/process.go#L25)) - this was because I already had access to the executing user and it made sense to be lazy and just place it there. I believe I've already introduced the possibility to specify the destination path, as we've talked about being able to specify it would be beneficial.
2. Extracting the archive in any of the cases (either .zip, .tar or .gz) places the extracted files next to the connector itself by default. I don't remember having specified the destination folder, so I think that's the default way it works.

Currently, as you mentioned, it's a bit inconsistent, and we should fix that in the connector.

In my opinion, we should create a folder (for example, `dumps` or `imports` or something along that line) next to the connector (like in the case of the `sql` folder) and both download the dumps there and move the extracted files there as well before starting the import / others.

What do you think?

**Comment by sorin-pop** [comment]
I agree, sounds good to me.
