### ISSUE TITLE
MySQL 5.5.49

### ISSUE THREAD

**Issue by ZoltanTakacs** [djavorszky/ddn#65]
Creating a new DB results an error msg:
sending json message failed: sending request failed: Post http://jabba.liferay.int:7100/create-database: dial tcp 192.168.211.8:7100: getsockopt: connection refused

**Comment by ZoltanTakacs** [comment]
![clipboard02](https://cloud.githubusercontent.com/assets/2045409/24287130/9b16e8a8-1078-11e7-97ef-bb3f751035f4.jpg)

**Comment by djavorszky** [comment]
Thanks for reporting this Zoltan, I'll look into this.

Dani

**Comment by djavorszky** [comment]
Issue arose because the connector went away.

It went away because it's running in a docker container, which is running in a server. The server was restarted (due to an electricity outage), which started the container with its default parameters.

I did not update the default parameters, meaning, the container no longer holds the connector. Since there was an outage, the connector could not report it leaving the swarm.

Resolution: Recreate connector on container, update container default values. Also implement #67.

**Comment by djavorszky** [comment]
Turns out you can revive old containers, which I just did.

@ZoltanTakacs, can you please recheck? It should work now without issues.

**Comment by ZoltanTakacs** [comment]
Yeah, it works now. See https://github.com/djavorszky/ddn/issues/68 :) 
Thanks Dani!
