### ISSUE TITLE
Ability to browse and import DB files from r2

### ISSUE THREAD

**Issue by ZoltanTakacs** [djavorszky/ddn#66]
It would be great and much time / space efficient if we can point directly to the DB dump on r2d2

**Comment by djavorszky** [comment]
I agree that this feature would be nice to have, however I'd like to generalize it, meaning, that it would be nice to be able to specify a root directory for the server which the end user could browse for dumps (so that the implementation would not be tied to r2d2).

For now, I placed it into Backlog because I anticipate it would require quite some time to implement.

**Comment by NorbertKocsis** [comment]
+1 for this feature :)

**Comment by sorin-pop** [comment]
I'd just like to clarify Zoli's initial feature description, as "we can point directly to the DB dump on r2d2" can somewhat be misunderstood.

In the new CloudDB the user can easily select a file from r2d2, if r2d2 is mapped/mounted on his machine. And that should be the case with everyone here in the office. Additionally, you can also select a file from your local PC as well (or another mapped network drive, external HD, etc.), which I think is a superior user experience and flexibility, compared to the old Cloud DB.

It's true, now the dump file selected from r2d2 will be uploaded to the Cloud DB server through the client PC (browser), not directly from r2d2 to the cloud server. And probably that's what Zoli meant, that this is not time and space efficient.
Personally I don't think it's a big deal, but we can do this if you want (Dani, it's up to you). I just wanted to make sure and clarify that this should not mean returning to the "limited" dump selection method of the old Cloud DB.

**Comment by djavorszky** [comment]
Yup, I understand the request, and even if we implement something like that, we'll not be taking away the current functionality.

What I want to do is decouple it from r2d2, and instead be able to add folder in which the end users can browse for files, so that the server is not tied to one particular server.

**Comment by NorbertKocsis** [comment]
As a workaround until this happens could the old version be made working again? I tried to use that but it failed with the following error:
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)

**Comment by djavorszky** [comment]
Implemented as of ed3e3e8c3491b873d7c71c3f13ec3791a40cdcbf

**Comment by ZoltanTakacs** [comment]
Great! Thanks Dani! :) 👍

**Comment by NorbertKocsis** [comment]
Cool! Thx! 🍺
