### ISSUE TITLE
Mysql database creation fails if the user already exists

### ISSUE THREAD

**Issue by sorin-pop** [djavorszky/ddn#84]
... but I think it should not. Users should be able (actually recommended) to always use the same user/password for mysql (like Alfonso does).

**Comment by djavorszky** [comment]
This is a trivial change when creating a database - only create user if it does not exist, otherwise continue on.

What's harder is what to do when dropping a database, as right now, the user is also dropped - however, that would kill the other access.

We could query the database to see the number of grants the user has (SHOW GRANTS FOR username), however, I can't seem to find a way to count the returned rows, and only drop the user if that's the last database it is assigned to..

**Comment by sorin-pop** [comment]
Good approach, hope you will find some way to count those rows.

If not, an alternative would be to never drop the user. But this way the users will remain and accumulate in the database, although I don't think they occupy a lot of space.

**Comment by djavorszky** [comment]
:+1:  Figured it out! Revoking privileges, then checking how many privileges the user has, and if zero (no more databases), then dropping user.

Implemented as of e55ec2d

Cheers
